<?php
$plang = array(
"alt_bolumler" => "Subsections",

"my_account"=>"My account",
"atelier801_account"=>$ayarlar['title']." account",
"email_change"=>"Change E-mail",
"pw_change"=>"Change password",
"nick_change"=>"Change nickname",
"buy_fraises"=>"Купи Ягоди",
"verification_code"=>"Code",
"have_fraises"=>"You currently have <span class='nombre-fraises'> %s </span> fraises.",
"fraises_offer"=>"(%s free)",
"loading"=>"Loading...",
"verification_required"=>"You must validate your account in order to be able to edit account settings.",
"verification_request"=>"Verification request",
"verification_entercode"=>"Please enter the validation code you received in your mailbox.",
"verification_unsuccessful"=>"The certification code you entered is invalid.",
 
"language"=>"Language",
"forums"=>"Форуми",
"dev_tracker"=>"Dev Tracker",
"arama"=>"Търси",
"Inbox"=>"Пощенска кутия",
"last_posts"=>"Last posts",
"favorite_topics"=>"Favorite topics",
"favorite_tribes"=>"Favorite tribes",
"my_profile"=>"Моят профил",
"my_friends"=>"Моите приятели",
"blacklist"=>"Черен списък",
"my_tribe"=>"Моето племе",
"tribe_profile"=>"Профил на племето",
"tribe_forum"=>"Форум на племето",
"see_members"=>"Виж членове",
 
"contact"=>"Contact",
"required_nick"=>"Username (required)",
"contact_text"=>"Got something to say ? A suggestion, something you would like to be changed on ".$ayarlar['title']." ? Write to us here !",
"required_email"=>"Email address (required)",
"category"=>"Category",
"contact_1"=>"Payment problem",
"contact_2"=>"Email change",
"contact_4"=>"Password lost",
"contact_6"=>"Feedback",
"contact_7"=>"Business-related",
"contact_8"=>"Other",
"subject"=>"Subject",
"topic_message"=>"Съобщение",
 
"chat"=>"Chat",
"conversation_deleted"=>"You can no longer answer because the other person has deleted this conversation completely.",
 
"mark_not_seen"=>"Mark as unread",
"started_at_date1"=>"Започна ",
"started_at_date2"=>"",
"tumunu_sec"=>"Select all",
"tumunu_sec_kaldir"=>"Unselect all",
"new_dialog"=>"Ново съобщение",
"new_discussion"=>"Нова дискусия",
"new_private_poll"=>"Нова частна анкета ",
"empty_trash"=>"Изпразни коша",
"delete_permanently"=>"Permanently delete",
"inbox"=>"Пощенска кутия",
"trash"=>"Кошче",
 
"topic"=>"Тема",
"topic_createdby1"=>" Започна от ",
"topic_createdby2"=>" на ",
"topic_createdby3"=>"",
"delete_favoritetopic"=>"Изтрий любими",
 
"favorite"=>"Favorite",
 
"team"=>"Staff",
"privacy"=>"Privacy Policy",
"version"=>"Version ".$ayarlar['version'],
"terms_cookie"=>"This website uses cookies to improve your user experience.",
"accept_text"=>"I understand",
"terms_polit"=>"Privacy Policy",
 
"reset_password"=>"Reset password",
"sifre"=>"Password",
"tekrar"=>"Again",
"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Someone, hopefully you, has requested to validate your  '.$ayarlar['title'].' account %1</p>

<p>For your select setting, please copy the following code into the appropriate input field in game : </p><h1>%2</h1><p></p>

<p>If you didn\'t request it, you can ignore this email.</p>
</div>

',
 

"login_keeplogged"=>"Keep me logged in",
"login_or"=>"or",
 
"to_who"=>"До",
"message_subject"=>"Предмет",
"dialog_yourself"=>"Играчите са невалидни, игнорират ви или са в черния ви списък.",
 
"new_forum"=>"New Forum",
"edit_forum"=>"Edit Forum",
 
"new_section"=>"Нова секция",
"edit_section"=>"Редактиране",
 
"topic_name"=>"Титла",
"bold"=>"Удебелено",
"italic"=>"Наклонено",
"underlined"=>"Подчертано",
"strikethrough"=>"Strikethrough",
"colorhex"=>"Цвят(в HEX)",
"size"=>"Размер",
"small"=>"Малък",
"large"=>"Голям",
"huge"=>"Много голям",
"font"=>"Шрифт",
"alignment"=>"Параграф",
"left"=>"Ляво",
"right"=>"Дясно",
"center"=>"Център",
"justify"=>"Justify",
"seperation"=>"Horizontal ruler",
"table"=>"Table",
"image"=>"Изображение: сложи url между таговете",
"uitab"=>"Етикети: сложи името след # между тагове",
"leftalign"=>"Подравняване на ляво",
"rightalign"=>"Подравняване на дясно",
"centeralign"=>"Центрирано",
"link"=>"Линк",
"list"=>"Списък",
"quote"=>"Цитат",
"lock"=>"Спойлер",
"previsualisation"=>"Преглед",
"previsualisation_hide"=>"Скрий",
 
"messages"=>"Съобщения",
"prestige"=>"Prestige",
"profile_level"=>"Level",
"profile_birth"=>"Рожден ден",
"profile_location"=>"Район",
"show_ifonline"=>"Display online status",
"online"=>"Online",
"offline"=>"Offline",
"sanctions"=>"Санкции",
"ban_type"=>"Тип",
"ban_time"=>"Времетраене",
"ban_created"=>"Creation",
"ban_start"=>"Начало",
"ban_end"=>"Край",
"ban_status"=>"Състояние",
"ban_active"=>"Активен",
"ban_ended"=>"Ended",
"ban_hour"=>"час(а)",
"profile"=>"Профил",
"send_message"=>"Изпрати съобщение",
"change_avatar"=>"Смени аватар",
"remove_avatar"=>"Remove Avatar",
"edit_profile"=>"Edit profile",
"parameters"=>"Parameters",
"message_more"=>"More",
"message_less"=>"Less",
"started_topics"=>"Topics started",
"profiles"=>"Профили",
 
"new_topic"=>"Нова тема",
"new_forum_poll"=>"Нова анкета",
"pin"=>"Postit",
"unpin"=>"Unpostit",
"lockf"=>"Затворена",
"unlock"=>"Активен",
"filter_view"=>"Filter display",
"deleted_topics"=>"изтрити теми",
 
"name"=>"Name",
"admins"=>"Admins",
"mods"=>"Moderators",
"sentinels"=>"Sentinels",
"mappers"=>"Map crews",
 
"add_favoritetopic"=>"Add from favorites",
"mudahale"=>"Moderated by %s, reason: %s",
"mudahale_text"=>"Moderate",
"last_edit"=>"Last edit:",
"topic_locked"=>"Topic locked",
 
"started_at_by"=>"by %s on %s",
 
"change_logo"=>"Change logo",
"remove_logo"=>"Remove logo",
"tribe_open"=>"Open",
"tribe_closed"=>"Closed",
"show_tribemessage"=>"Show tribal message",
"show_tribedescription"=>"Show description",
"tribe_message"=>"Tribal message",
"tribe_history"=>"Tribe history",
"tribes"=>"Tribes",
"page_next"=>"Next",
"page_last"=>"Last",
 
"email"=>"E-mail",
"isim"=>"Name",
"report_short"=>"Your report should consist of at least 3 words.",
 
"reconnection"=>"Connecting again...",
"autolang_error"=>"Automatic language opened because your language is not in the system.",
"not_found"=>"Not found",
"404_page"=>"Page not found.",
"reward"=>"Reward",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Day(s)",
"saat"=>"Hour(s)",
"dakika"=>"Minute(s)",
"saniye"=>"Second(s)",
"reward_left"=>"Left",
"buy_hazelnut"=>"Buy hazelnuts",
"have_hazelnut"=>"You currently have <span class='nombre-hazelnut'> %s </span> hazelnuts.",
 
"account_newemail"=>"New E-mail",
"account_code_verifed"=>"Successful validation. You can now edit account settings.",
"namechange_fraises"=>"Changing your name requires %s fraises.",
"namechange_newname"=>"New Name",
"account_shortlongname"=>"The name must be at least 3 characters and at most 15 characters.",
"account_fraisesnotenough"=>"Fraises is insufficient.",
"account_nameinusage"=>"This username is being used.",
"account_nameinusagebyyou"=>"You already use this username.",
"account_shortlongpw"=>"Password must be at least 8 characters and at most 16 characters.",
"account_pwsnotmatch"=>"Both your passwords must be identical.",
"account_pwchanged"=>"The password was changed !",
"account_blankemail"=>"E-mail field should not be left blank.",
"account_fakeemail"=>"Invalid email.",
"account_emailchanged"=>"E-mail has been changed!",
"verification_newpassword"=>"New password",
"verification_passwordvf"=>"Password verification",
"verification_exitall"=>"Sign out from all devices",
"move"=>"Move"

);

?>
