<?php
$plang = array(
"alt_bolumler" => "Subseções",

"tumunu_sec"=>"Selecionar tudo",
"tumunu_sec_kaldir"=>"Desmarque todos",
"favorite_topics"=>"Tópicos favoritos",
"favorite_tribes"=>"Tribos favoritas",
"topic_createdby1"=>" Iniciado por ",
"topic_createdby2"=>" em ",
"topic_createdby3"=>"",
"tribes"=>"Tribos",
"profiles"=>"Perfis",
"my_friends"=>"Meus amigos",
"blacklist"=>"Lista negra",
"last_posts"=>"Últimos posts",
"started_topics"=>"Tópicos iniciados",
"forums"=>"Fóruns",
"new_topic"=>"Novo topico",
"new_forum_poll"=>"Nova votação",
"Inbox"=>"Conversas",
"new_dialog"=>"Nova mensagem",
"new_discussion"=>"Nova discussão",
"new_private_poll"=>"Nova pesquisa privada",
"empty_trash"=>"Lixo vazio",
"delete_permanently"=>"Excluir permanentemente",
"inbox"=>"Caixa de entrada",
"trash"=>"Lixeria",
"dev_tracker"=>"Posts dos Admins",
"my_account"=>"Conta",
"my_profile"=>"Meu perfil",
"my_tribe"=>"Minha tribo",
"tribe_profile"=>"Perfil da tribo",
"tribe_forum"=>"Fórum da tribo",
"see_members"=>"Ver membros",
"tribe_history"=>"História da tribo",
"language"=>"Langue",
"team"=>"Staff",
"privacy"=>"Política de Privacidade",
"contact"=>"Contato",
"version"=>"Versão ".$ayarlar['version'],
"mudahale"=>"Moderado por %s, motivo: %s",
"mudahale_text"=>"Moderado",
"reconnection"=>"Conecte-se novamente ...",
"bold"=>"Negrito",
"italic"=>"Itálico",
"underlined"=>"Sublinhado",
"strikethrough"=>"Tachado",
"colorhex"=>"Cor (em hexadecimal)",
"size"=>"Tamanho",
"small"=>"Pequeno",
"large"=>"Ampla",
"huge"=>"Enorme",
"font"=>"Fonte",
"alignment"=>"Parágrafo",
"left"=>"Esquerdo",
"right"=>"Certo",
"center"=>"Centro",
"justify"=>"Justificar",
"seperation"=>"Separação",
"table"=>"Mesa",
"image"=>"Imagem: coloque o URL entre as tags",
"uitab"=>"Guias: coloque o nome após o # entre as tags",
"leftalign"=>"Esquerda alinhada",
"rightalign"=>"Alinhado à direita",
"centeralign"=>"Centrado",
"link"=>"Ligação",
"list"=>"Lista",
"quote"=>"Citar",
"lock"=>"Spoiler",
"previsualisation"=>"Pré-visualização",
"previsualisation_hide"=>"ocultar",
"page_next"=>"Próximo",
"page_last"=>"Último",
"online"=>"Conectados",
"offline"=>"Desligado",
"profile"=>"Perfil",
"send_message"=>"Enviar mensagem",
"change_avatar"=>"Mudar Avatar",
"remove_avatar"=>"Remover Avatar",
"edit_profile"=>"Editar Perfil",
"parameters"=>"Parâmetros",

"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Alguém, espero que você, solicitou a validação da sua conta '.$ayarlar['title'].' %1</p>

<p>Para sua configuração de seleção, copie o seguinte código no campo de entrada apropriado no jogo: </p><h1>%2</h1><p></p>

<p>Se você não solicitou, pode ignorar este e-mail.</p>
</div>

',

"sifre"=>"Senha",
"email"=>"O email",
"isim"=>"Nome",
"messages"=>"Mensagens",
"prestige"=>"Prestígio",
"show_ifonline"=>"Exibir status online",
"sanctions"=>"Sanções",
"ban_type"=>"Punir tipo",
"ban_time"=>"Tempo",
"ban_created"=>"Criar hora",
"ban_start"=>"Começar",
"ban_end"=>"Fim",
"ban_status"=>"Status",
"ban_active"=>"Ativo",
"ban_ended"=>"Terminado",
"ban_hour"=>"Hora",
"message_more"=>"Consulte Mais informação",
"message_less"=>"Ler menos",
"atelier801_account"=>$ayarlar['title']." da conta",
"email_change"=>"Mude o e-mail",
"pw_change"=>"Mudar senha",
"nick_change"=>"Alterar apelido",
"buy_fraises"=>"Compre fraises",
"buy_hazelnut"=>"Compre hazelnut",
"verification_required"=>"Você deve validar sua conta para poder editar as configurações da conta.",
"verification_request"=>"Pedido de verificação",
"have_fraises"=>"Atualmente, você tem <span class='nombre-fraises'> %s </span> fraises.",
"have_hazelnut"=>"Atualmente, você tem <span class='nombre-hazelnut'> %s </span> hazelnut.",
"fraises_offer"=>"(%s grátis)",
"loading"=>"Carregando...",
"chat"=>"Bate-papo",
"conversation_deleted"=>"Você não pode mais responder porque a outra pessoa excluiu completamente esta conversa.",
"mark_not_seen"=>"marcar como não lido",
"started_at_date1"=>"Começou em",
"topic"=>"Tópico",
"delete_favoritetopic"=>"Excluir dos favoritos",
"add_favoritetopic"=>"Adicionar dos favoritos",
"favorite"=>"Favorito",
"reset_password"=>"Redefinir senha",
"verification_entercode"=>"Digite o código de validação que você recebeu na sua caixa de correio.",
"verification_code"=>"Código",
"verification_newpassword"=>"Nova senha",
"verification_passwordvf"=>"Verificação de senha",
"verification_exitall"=>"Sair de todos os dispositivos",
"verification_unsuccessful"=>"O código de certificação que você digitou é inválido.",
"login_keeplogged"=>"O login mantém-se logado",
"login_or"=>"ou",
"change_logo"=>"Alterar logotipo",
"remove_logo"=>"Remover logotipo",
"tribe_open"=>"Abrir",
"tribe_closed"=>"Fechadas",
"show_tribemessage"=>"Mostrar mensagem tribal",
"show_tribedescription"=>"Mostre a descrição",
"tribe_message"=>"Mensagem tribal",
"started_at_by"=>"Iniciado por %s em %s",
"name"=>"Nome",
"admins"=>"Admins",
"mods"=>"Moderadores",
"sentinels"=>"Sentinelas",
"mappers"=>"Map Crew",
"filter_view"=>"Exibição do filtro",
"deleted_topics"=>"Tópicos excluídos",
"subject"=>"Sujeito",
"to_who"=>"Para",
"topic_name"=>"Título",
"topic_message"=>"Mensagem",
"account_newemail"=>"Novo Email",
"account_code_verifed"=>"Validação bem sucedida. Agora você pode editar as configurações da conta.",
"namechange_fraises"=>"Alterar seu nome requer %s fraises.",
"namechange_newname"=>"Novo nome",
"account_shortlongname"=>"O nome deve ter no mínimo 3 caracteres e no máximo 15 caracteres.",
"account_fraisesnotenough"=>"Fraudes é insuficiente.",
"account_nameinusage"=>"Este nome de usuário está sendo usado.",
"account_nameinusagebyyou"=>"Você já usa esse nome de usuário.",
"account_shortlongpw"=>"A senha deve ter no mínimo 8 caracteres e no máximo 16 caracteres.",
"account_pwsnotmatch"=>"Suas duas senhas devem ser idênticas.",
"account_pwchanged"=>"A senha foi alterada!",
"account_blankemail"=>"O campo email não deve ser deixado em branco.",
"account_fakeemail"=>"E-mail inválido.",
"account_emailchanged"=>"O email foi alterado!",
"report_short"=>"Seu relatório deve consistir em pelo menos três palavras.",
"topic_locked"=>"Tópico bloqueado",
"dialog_yourself"=>"Você não pode enviar mensagens para si mesmo!",
"arama"=>"Procurar",
"new_forum"=>"Novo Fórum",
"edit_forum"=>"Editar Fórum",
"new_section"=>"Nova Seção",
"edit_section"=>"Editar seção",
"required_nick"=>"Nome de usuário (necessário)",
"contact_text"=>"Algo a dizer? Uma sugestão, algo que você gostaria de mudar no ".$ayarlar['title']." ? Escreva para nós aqui!",
"required_email"=>"E-mail (Obrigatório)",
"category"=>"Categoria",
"contact_1"=>"Problema de pagamento",
"contact_2"=>"Mudança de email",
"contact_4"=>"Senha perdida",
"contact_6"=>"Comentários",
"contact_7"=>"Relacionado aos negócios",
"contact_8"=>"De outros",
"not_found"=>"Não encontrado",
"pin"=>"Constantes",
"unpin"=>"un Constantes",
"lockf"=>"Bloquear",
"unlock"=>"Destravar",
"404_page"=>"Página não encontrada.",
"last_edit"=>"Última edição:",
"terms_cookie"=>"Este site usa cookies para melhorar sua experiência de usuário.",
"accept_text"=>"Compreendo",
"terms_polit"=>"Política de Privacidade",
"autolang_error"=>"Idioma automático aberto porque seu idioma não está no sistema.",
"tekrar"=>"Novamente",
"reward"=>"Recompensa",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Dia(s)",
"saat"=>"Hora(s)",
"dakika"=>"Minuto(s)",
"saniye"=>"Segundo(s)",
"reward_left"=>"Esquerdo",
"move"=>"Move"

);

?>
