<?php
$plang = array(
"alt_bolumler" => "分区",

"my_account"=>"我的账号",
"atelier801_account"=>$ayarlar['title']."账号",
"email_change"=>"变更电子邮箱",
"pw_change"=>"变更登录密码",
"nick_change"=>"更换昵称",
"buy_fraises"=>"购买草莓",
"verification_code"=>"Code",
"have_fraises"=>"你当前拥有<span class='nombre-fraises'>%s</span>个草莓。",
"fraises_offer"=>" （赠送%s） ",
"loading"=>"载入中…",
"verification_required"=>"你必须要通过账号验证才能更改你的账号设置。",
"verification_request"=>"请求验证",
"verification_entercode"=>"请输入您的邮箱中收到的验证码。",
"verification_unsuccessful"=>"你输入的是无效代码。",
 
"language"=>"语言",
"forums"=>"论坛",
"dev_tracker"=>"追踪开发版本",
"arama"=>"搜索",
"Inbox"=>"收件箱",
"last_posts"=>"最后回复",
"favorite_topics"=>"收藏的主题",
"favorite_tribes"=>"收藏的部落",
"my_profile"=>"我的资料",
"my_friends"=>"我的好友",
"blacklist"=>"黑名单",
"my_tribe"=>"我的部落",
"tribe_profile"=>"部落资料",
"tribe_forum"=>"部落论坛",
"see_members"=>"查看成员",
 
"contact"=>"联系我们",
"required_nick"=>"名字（必填）",
"contact_text"=>"有什么想说的吗？比如对于".$ayarlar['title']."的建议？就在这里告诉我们吧！",
"required_email"=>"电子邮箱（必填）",
"category"=>"类别",
"contact_1"=>"支付问题",
"contact_2"=>"变更电子邮箱",
"contact_4"=>"密码遗失",
"contact_6"=>"反馈",
"contact_7"=>"商业合作",
"contact_8"=>"其他",
"subject"=>"标题",
"topic_message"=>"内容",
 
"chat"=>"Chat",
"conversation_deleted"=>"You can no longer answer because the other person has deleted this conversation completely.",
 
"mark_not_seen"=>"标记为未读",
"started_at_date1"=>"开始于",
"started_at_date2"=>"",
"tumunu_sec"=>"全选中",
"tumunu_sec_kaldir"=>"全不选",
"new_dialog"=>"新信息",
"new_discussion"=>"新建讨论组",
"new_private_poll"=>"新的私人投票",
"empty_trash"=>"清空垃圾桶",
"delete_permanently"=>"永久删除",
"inbox"=>"收件箱",
"trash"=>"垃圾桶",
 
"topic"=>"主题",
"topic_createdby1"=>"",
"topic_createdby2"=>"开始于",
"topic_createdby3"=>"",
"delete_favoritetopic"=>"移出收藏夹",
 
"favorite"=>"Favorite",
 
"team"=>"职员表",
"privacy"=>"隐私政策",
"version"=>"版本 ".$ayarlar['version'],
"terms_cookie"=>"本网站正使用Cookies来改善您的用户体验。",
"accept_text"=>"我明白了",
"terms_polit"=>"隐私政策",
 
"reset_password"=>"重置密码",
"sifre"=>"Password",
"tekrar"=>"Again",
"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Someone, hopefully you, has requested to validate your  '.$ayarlar['title'].' account %1</p>

<p>For your select setting, please copy the following code into the appropriate input field in game : </p><h1>%2</h1><p></p>

<p>If you didn\'t request it, you can ignore this email.</p>
</div>

',
 

"login_keeplogged"=>"保持我的登录状态",
"login_or"=>"或",
 
"to_who"=>"发送给",
"message_subject"=>"主题",
"dialog_yourself"=>"该玩家无效，可能他屏蔽了你或者在你的黑名单中。",
 
"new_forum"=>"New Forum",
"edit_forum"=>"Edit Forum",
 
"new_section"=>"新建分区",
"edit_section"=>"编辑",
 
"topic_name"=>"标题",
"bold"=>"粗体",
"italic"=>"斜体",
"underlined"=>"下划线",
"strikethrough"=>"删除线",
"colorhex"=>"颜色（十六进制）",
"size"=>"字号",
"small"=>"小",
"large"=>"大",
"huge"=>"特大",
"font"=>"字形",
"alignment"=>"段落",
"left"=>"靠左对齐",
"right"=>"靠右对齐",
"center"=>"居中",
"justify"=>"两端对齐",
"seperation"=>"分割线",
"table"=>"表格",
"image"=>"图像: 把url放在标签中间",
"uitab"=>"标签：把名字放在标签之间，#的后面。",
"leftalign"=>"靠左对齐",
"rightalign"=>"靠右对齐",
"centeralign"=>"居中",
"link"=>"链接",
"list"=>"列表",
"quote"=>"引用",
"lock"=>"展开",
"previsualisation"=>"预览",
"previsualisation_hide"=>"隐藏",
 
"messages"=>"信息",
"prestige"=>"威望",
"profile_level"=>"等级",
"profile_birth"=>"生日",
"profile_location"=>"位置",
"show_ifonline"=>"显示在线状态",
"online"=>"在线",
"offline"=>"离线",
"sanctions"=>"封禁",
"ban_type"=>"类型",
"ban_time"=>"期限",
"ban_created"=>"创建日期",
"ban_start"=>"开始于",
"ban_end"=>"失效日期",
"ban_status"=>"状态",
"ban_active"=>"有效",
"ban_ended"=>"Ended",
"ban_hour"=>"小时",
"profile"=>"资料",
"send_message"=>"发送信息",
"change_avatar"=>"更改头像",
"remove_avatar"=>"移除头像",
"edit_profile"=>"编辑资料",
"parameters"=>"参数",
"message_more"=>"展开",
"message_less"=>"缩略",
"started_topics"=>"发起的主题",
"profiles"=>"个人资料",
 
"new_topic"=>"新主题",
"new_forum_poll"=>"新投票",
"pin"=>"置顶",
"unpin"=>"Unpin",
"lockf"=>"关闭",
"unlock"=>"有效",
"filter_view"=>"显示筛选器",
"deleted_topics"=>"已删除的主题",
 
"name"=>"Name",
"admins"=>"Admins",
"mods"=>"Moderators",
"sentinels"=>"Sentinels",
"mappers"=>"Map crews",
 
"add_favoritetopic"=>"Add from favorites",
"mudahale"=>"Moderated by %s, reason: %s",
"mudahale_text"=>"Moderate",
"last_edit"=>"Last edit:",
"topic_locked"=>"Topic locked",
 
"started_at_by"=>"by %s on %s",
 
"change_logo"=>"Change logo",
"remove_logo"=>"Remove logo",
"tribe_open"=>"Open",
"tribe_closed"=>"Closed",
"show_tribemessage"=>"Show tribal message",
"show_tribedescription"=>"Show description",
"tribe_message"=>"Tribal message",
"tribe_history"=>"Tribe history",
"tribes"=>"Tribes",
"page_next"=>"Next",
"page_last"=>"Last",
 
"email"=>"E-mail",
"isim"=>"Name",
"report_short"=>"Your report should consist of at least 3 words.",
 
"reconnection"=>"Connecting again...",
"autolang_error"=>"Automatic language opened because your language is not in the system.",
"not_found"=>"Not found",
"404_page"=>"Page not found.",
"reward"=>"Reward",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Day(s)",
"saat"=>"Hour(s)",
"dakika"=>"Minute(s)",
"saniye"=>"Second(s)",
"reward_left"=>"Left",
"buy_hazelnut"=>"Buy hazelnuts",
"have_hazelnut"=>"You currently have <span class='nombre-hazelnut'> %s </span> hazelnuts.",
 
"account_newemail"=>"New E-mail",
"account_code_verifed"=>"Successful validation. You can now edit account settings.",
"namechange_fraises"=>"Changing your name requires %s fraises.",
"namechange_newname"=>"New Name",
"account_shortlongname"=>"The name must be at least 3 characters and at most 15 characters.",
"account_fraisesnotenough"=>"Fraises is insufficient.",
"account_nameinusage"=>"This username is being used.",
"account_nameinusagebyyou"=>"You already use this username.",
"account_shortlongpw"=>"Password must be at least 8 characters and at most 16 characters.",
"account_pwsnotmatch"=>"Both your passwords must be identical.",
"account_pwchanged"=>"The password was changed !",
"account_blankemail"=>"E-mail field should not be left blank.",
"account_fakeemail"=>"Invalid email.",
"account_emailchanged"=>"E-mail has been changed!",
"verification_newpassword"=>"New password",
"verification_passwordvf"=>"Password verification",
"verification_exitall"=>"Sign out from all devices",
"move"=>"Move"

);

?>
