<?php
$plang = array(
"alt_bolumler" => "Unterkategorien",
"my_account"=>"Mein Account",
"atelier801_account"=>$ayarlar['title']." Account",
"email_change"=>"E-Mail ändern",
"pw_change"=>"Passwort wechseln",
"nick_change"=>"Namen ändern",
"buy_fraises"=>"Erdbeeren kaufen",
"verification_code"=>"Code",
"have_fraises"=>"Du hast zur Zeit <span class='nombre-fraises'>%s</span> Erdbeeren.",
"fraises_offer"=>"(%s angeboten)",
"loading"=>"Laden...",
"verification_required"=>"Du musst deinen Account bestätigen um die Einstellungen anzupassen.",
"verification_request"=>"Auftragsbestätigung",
"verification_entercode"=>"Bitte füge den Code ein, den du per E-Mail erhalten hast.",
"verification_unsuccessful"=>"Der Code, den du eingegeben hast, ist ungültig.",
 
"language"=>"Sprache",
"forums"=>"Foren",
"dev_tracker"=>"Dev Tracker",
"arama"=>"Suche",
"Inbox"=>"Posteingang",
"last_posts"=>"Zuletzt gepostet",
"favorite_topics"=>"Favorisierte Themen",
"favorite_tribes"=>"Favorisierte Stämme",
"my_profile"=>"Mein Profil",
"my_friends"=>"Meine Freunde",
"blacklist"=>"Schwarze Liste",
"my_tribe"=>"Mein Stamm",
"tribe_profile"=>"Stammprofil",
"tribe_forum"=>"Stammforum",
"see_members"=>"Mitglieder ansehen",
 
"contact"=>"Kontakte",
"required_nick"=>"Username (erforderlich)",
"contact_text"=>"Möchtest du uns etwas sagen? Ein Vorschlag, etwas, was du an ".$ayarlar['title']." verändern würdest? Schreib uns hier!",
"required_email"=>"E-Mail Adresse (erforderlich)",
"category"=>"Kategorie",
"contact_1"=>"Zahlungsproblem",
"contact_2"=>"E-Mail ändern",
"contact_4"=>"Vergessenes Passwort",
"contact_6"=>"Feedback",
"contact_7"=>"Geschäftliche Gründe",
"contact_8"=>"Anderes",
"subject"=>"Betreff",
"topic_message"=>"Nachricht",
 
"chat"=>"Chat",
"conversation_deleted"=>"You can no longer answer because the other person has deleted this conversation completely.",
 
"mark_not_seen"=>"Als ungelesen markieren",
"started_at_date1"=>"Beginn um",
"started_at_date2"=>"",
"tumunu_sec"=>"Alles auswählen",
"tumunu_sec_kaldir"=>"Auswahl zurücksetzen",
"new_dialog"=>"Neue Nachricht",
"new_discussion"=>"Neue Diskussion",
"new_private_poll"=>"Neue private Umfrage",
"empty_trash"=>"Papierkorb leeren",
"delete_permanently"=>"Dauerhaft löschen ",
"inbox"=>"Posteingang",
"trash"=>"Mülleimer",
 
"topic"=>"Thema",
"topic_createdby1"=>" Gestartet von ",
"topic_createdby2"=>" am ",
"topic_createdby3"=>"",
"delete_favoritetopic"=>"Favorit löschen",
 
"favorite"=>"Favorite",
 
"team"=>"Staff",
"privacy"=>"Datenschutzregelungen",
"version"=>"Version ".$ayarlar['version'],
"terms_cookie"=>"Diese Seite verwendet Cookies um deinen Besuch so gut wie möglich zu gestalten.",
"accept_text"=>"Ich habe es verstanden.",
"terms_polit"=>"Datenschutzregelungen",
 
"reset_password"=>"Passwort zurücksetzen",
"sifre"=>"Password",
"tekrar"=>"Again",
"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Someone, hopefully you, has requested to validate your  '.$ayarlar['title'].' account %1</p>

<p>For your select setting, please copy the following code into the appropriate input field in game : </p><h1>%2</h1><p></p>

<p>If you didn\'t request it, you can ignore this email.</p>
</div>

',
 

"login_keeplogged"=>"Eingeloggt lassen",
"login_or"=>"ODER",
 
"to_who"=>"An",
"message_subject"=>"Betreff",
"dialog_yourself"=>"Die Spieler sind ungültig, ignorieren dich oder sind auf deiner Blacklist.",
 
"new_forum"=>"New Forum",
"edit_forum"=>"Edit Forum",
 
"new_section"=>"Neues Unterforum",
"edit_section"=>"Bearbeiten",
 
"topic_name"=>"Titel",
"bold"=>"Fett",
"italic"=>"Kursiv",
"underlined"=>"Unterstrichen",
"strikethrough"=>"Durchgestrichen",
"colorhex"=>"Farbe (in hexadezimal)",
"size"=>"Größe",
"small"=>"Klein",
"large"=>"Groß",
"huge"=>"Sehr groß",
"font"=>"Schriftart",
"alignment"=>"Absatz",
"left"=>"Links",
"right"=>"Rechts",
"center"=>"Mittig",
"justify"=>"Im Block anordnen",
"seperation"=>"Horizontales Lineal",
"table"=>"Tabelle",
"image"=>"Bild: füge die url zwischen die tags ein",
"uitab"=>"Tabs: füge den namen hinter das # zwischen den tags ein",
"leftalign"=>"Linksbündig",
"rightalign"=>"Rechtsbündig",
"centeralign"=>"Mittig",
"link"=>"Link",
"list"=>"Liste",
"quote"=>"Zitat",
"lock"=>"Spoiler",
"previsualisation"=>"Vorschau",
"previsualisation_hide"=>"Verstecken",
 
"messages"=>"Nachrichten",
"prestige"=>"Prestige",
"profile_level"=>"Level",
"profile_birth"=>"Geburtstag",
"profile_location"=>"Wohnort",
"show_ifonline"=>"Online Status anzeigen",
"online"=>"Online",
"offline"=>"Offline",
"sanctions"=>"Sanktionen",
"ban_type"=>"Typ",
"ban_time"=>"Dauer",
"ban_created"=>"Kreation",
"ban_start"=>"Anfang",
"ban_end"=>"Ende",
"ban_status"=>"Zustand",
"ban_active"=>"Aktiv",
"ban_ended"=>"Ended",
"ban_hour"=>"Stunde(n)",
"profile"=>"Profil",
"send_message"=>"Nachricht versenden",
"change_avatar"=>"Avatar ändern",
"remove_avatar"=>"Avatar entfernen",
"edit_profile"=>"Profil bearbeiten",
"parameters"=>"Parameter",
"message_more"=>"Mehr",
"message_less"=>"Weniger",
"started_topics"=>"Themen gestartet",
"profiles"=>"Profile",
 
"new_topic"=>"Neuer Thread",
"new_forum_poll"=>"Neue Umfrage",
"pin"=>"Fixieren",
"unpin"=>"Unpin",
"lockf"=>"Geschlossen",
"unlock"=>"Aktiv",
"filter_view"=>"Filter anzeigen",
"deleted_topics"=>"gelöschte Themen",
 
"name"=>"Name",
"admins"=>"Admins",
"mods"=>"Moderators",
"sentinels"=>"Sentinels",
"mappers"=>"Map crews",
 
"add_favoritetopic"=>"Add from favorites",
"mudahale"=>"Moderated by %s, reason: %s",
"mudahale_text"=>"Moderate",
"last_edit"=>"Last edit:",
"topic_locked"=>"Topic locked",
 
"started_at_by"=>"by %s on %s",
 
"change_logo"=>"Change logo",
"remove_logo"=>"Remove logo",
"tribe_open"=>"Open",
"tribe_closed"=>"Closed",
"show_tribemessage"=>"Show tribal message",
"show_tribedescription"=>"Show description",
"tribe_message"=>"Tribal message",
"tribe_history"=>"Tribe history",
"tribes"=>"Tribes",
"page_next"=>"Next",
"page_last"=>"Last",
 
"email"=>"E-mail",
"isim"=>"Name",
"report_short"=>"Your report should consist of at least 3 words.",
 
"reconnection"=>"Connecting again...",
"autolang_error"=>"Automatic language opened because your language is not in the system.",
"not_found"=>"Not found",
"404_page"=>"Page not found.",
"reward"=>"Reward",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Day(s)",
"saat"=>"Hour(s)",
"dakika"=>"Minute(s)",
"saniye"=>"Second(s)",
"reward_left"=>"Left",
"buy_hazelnut"=>"Buy hazelnuts",
"have_hazelnut"=>"You currently have <span class='nombre-hazelnut'> %s </span> hazelnuts.",
 
"account_newemail"=>"New E-mail",
"account_code_verifed"=>"Successful validation. You can now edit account settings.",
"namechange_fraises"=>"Changing your name requires %s fraises.",
"namechange_newname"=>"New Name",
"account_shortlongname"=>"The name must be at least 3 characters and at most 15 characters.",
"account_fraisesnotenough"=>"Fraises is insufficient.",
"account_nameinusage"=>"This username is being used.",
"account_nameinusagebyyou"=>"You already use this username.",
"account_shortlongpw"=>"Password must be at least 8 characters and at most 16 characters.",
"account_pwsnotmatch"=>"Both your passwords must be identical.",
"account_pwchanged"=>"The password was changed !",
"account_blankemail"=>"E-mail field should not be left blank.",
"account_fakeemail"=>"Invalid email.",
"account_emailchanged"=>"E-mail has been changed!",
"verification_newpassword"=>"New password",
"verification_passwordvf"=>"Password verification",
"verification_exitall"=>"Sign out from all devices",
"move"=>"Move"

);

?>
