<?php
$plang = array(
"alt_bolumler" => "Subsections",
"my_account"=>"My account",
"atelier801_account"=>$ayarlar['title']." account",
"email_change"=>"Change E-mail",
"pw_change"=>"Change password",
"nick_change"=>"Change nickname",
"buy_fraises"=>"Buy fraises",
"verification_code"=>"Code",
"have_fraises"=>"You currently have <span class='nombre-fraises'> %s </span> fraises.",
"fraises_offer"=>"(%s free)",
"loading"=>"Loading...",
"verification_required"=>"You must validate your account in order to be able to edit account settings.",
"verification_request"=>"Verification request",
"verification_entercode"=>"Please enter the validation code you received in your mailbox.",
"verification_unsuccessful"=>"The certification code you entered is invalid.",
 
"language"=>"Language",
"forums"=>"Forums",
"dev_tracker"=>"Dev Tracker",
"arama"=>"Search",
"Inbox"=>"Conversations",
"last_posts"=>"Last posts",
"favorite_topics"=>"Favorite topics",
"favorite_tribes"=>"Favorite tribes",
"my_profile"=>"My profile",
"my_friends"=>"My friends",
"blacklist"=>"Blacklist",
"my_tribe"=>"My tribe",
"tribe_profile"=>"Tribe's profile",
"tribe_forum"=>"Tribe's forum",
"see_members"=>"See members",
 
"contact"=>"Contact",
"required_nick"=>"Username (required)",
"contact_text"=>"Got something to say ? A suggestion, something you would like to be changed on ".$ayarlar['title']." ? Write to us here !",
"required_email"=>"Email address (required)",
"category"=>"Category",
"contact_1"=>"Payment problem",
"contact_2"=>"Email change",
"contact_4"=>"Password lost",
"contact_6"=>"Feedback",
"contact_7"=>"Business-related",
"contact_8"=>"Other",
"subject"=>"Subject",
"topic_message"=>"Message",
 
"chat"=>"Chat",
"conversation_deleted"=>"You can no longer answer because the other person has deleted this conversation completely.",
 
"mark_not_seen"=>"Mark as unread",
"started_at_date1"=>"Started on",
"started_at_date2"=>"",
"tumunu_sec"=>"Select all",
"tumunu_sec_kaldir"=>"Unselect all",
"new_dialog"=>"New message",
"new_discussion"=>"New discussion",
"new_private_poll"=>"New private poll",
"empty_trash"=>"Empty trash",
"delete_permanently"=>"Permanently delete",
"inbox"=>"Inbox",
"trash"=>"Bin",
 
"topic"=>"Topic",
"topic_createdby1"=>" by ",
"topic_createdby2"=>" on ",
"topic_createdby3"=>"",
"delete_favoritetopic"=>"Delete from favorites",
 
"favorite"=>"Favorite",
 
"team"=>"Staff",
"privacy"=>"Privacy Policy",
"version"=>"Version ".$ayarlar['version'],
"terms_cookie"=>"This website uses cookies to improve your user experience.",
"accept_text"=>"I understand",
"terms_polit"=>"Privacy Policy",
 
"reset_password"=>"Reset password",
"sifre"=>"Password",
"tekrar"=>"Again",
"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Someone, hopefully you, has requested to validate your  '.$ayarlar['title'].' account %1</p>

<p>For your select setting, please copy the following code into the appropriate input field in game : </p><h1>%2</h1><p></p>

<p>If you didn\'t request it, you can ignore this email.</p>
</div>

',
 

"login_keeplogged"=>"Keep me logged in",
"login_or"=>"or",
 
"to_who"=>"To",
"message_subject"=>"Subject",
"dialog_yourself"=>"The players are invalid, ignoring you or are in your blacklist.",
 
"new_forum"=>"New Forum",
"edit_forum"=>"Edit Forum",
 
"new_section"=>"New Section",
"edit_section"=>"Edit",
 
"topic_name"=>"Title",
"bold"=>"Bold",
"italic"=>"Italic",
"underlined"=>"Underlined",
"strikethrough"=>"Strikethrough",
"colorhex"=>"Color (in hexadecimal)",
"size"=>"Size",
"small"=>"Small",
"large"=>"Large",
"huge"=>"Huge",
"font"=>"Font",
"alignment"=>"Paragraph",
"left"=>"Left",
"right"=>"Right",
"center"=>"Center",
"justify"=>"Justify",
"seperation"=>"Seperation",
"table"=>"Table",
"image"=>"Image: put the url between the tags",
"uitab"=>"Tabs: put the name after the # between tags",
"leftalign"=>"Left aligned",
"rightalign"=>"Right aligned",
"centeralign"=>"Centered",
"link"=>"Link",
"list"=>"List",
"quote"=>"Quote",
"lock"=>"Spoiler",
"previsualisation"=>"Preview",
"previsualisation_hide"=>"Hide",
 
"messages"=>"Messages",
"prestige"=>"Prestige",
"profile_level"=>"Level",
"profile_birth"=>"Birthday",
"profile_location"=>"Location",
"show_ifonline"=>"Display online status",
"online"=>"Online",
"offline"=>"Offline",
"sanctions"=>"Sanctions",
"ban_type"=>"Type",
"ban_time"=>"Duration",
"ban_created"=>"Creation",
"ban_start"=>"Start",
"ban_end"=>"End",
"ban_status"=>"State",
"ban_active"=>"Active",
"ban_ended"=>"Ended",
"ban_hour"=>"Hour(s)",
"profile"=>"Profile",
"send_message"=>"Send Message",
"change_avatar"=>"Change Avatar",
"remove_avatar"=>"Remove Avatar",
"edit_profile"=>"Edit profile",
"parameters"=>"Parameters",
"message_more"=>"More",
"message_less"=>"Less",
"started_topics"=>"Topics started",
"profiles"=>"Profiles",
 
"new_topic"=>"New topic",
"new_forum_poll"=>"New poll",
"pin"=>"Pin",
"unpin"=>"unPin",
"lockf"=>"Lock",
"unlock"=>"unLock",
"filter_view"=>"Filter display",
"deleted_topics"=>"Deleted topics",
 
"name"=>"Name",
"admins"=>"Admins",
"mods"=>"Moderators",
"sentinels"=>"Sentinels",
"mappers"=>"Map crews",
 
"add_favoritetopic"=>"Add from favorites",
"mudahale"=>"Moderated by %s, reason: %s",
"mudahale_text"=>"Moderate",
"last_edit"=>"Last edit:",
"topic_locked"=>"Topic locked",
 
"started_at_by"=>"by %s on %s",
 
"change_logo"=>"Change logo",
"remove_logo"=>"Remove logo",
"tribe_open"=>"Open",
"tribe_closed"=>"Closed",
"show_tribemessage"=>"Show tribal message",
"show_tribedescription"=>"Show description",
"tribe_message"=>"Tribal message",
"tribe_history"=>"Tribe history",
"tribes"=>"Tribes",
"page_next"=>"Next",
"page_last"=>"Last",
 
"email"=>"E-mail",
"isim"=>"Name",
"report_short"=>"Your report should consist of at least 3 words.",
 
"reconnection"=>"Connecting again...",
"autolang_error"=>"Automatic language opened because your language is not in the system.",
"not_found"=>"Not found",
"404_page"=>"Page not found.",
"reward"=>"Reward",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Day(s)",
"saat"=>"Hour(s)",
"dakika"=>"Minute(s)",
"saniye"=>"Second(s)",
"reward_left"=>"Left",
"buy_hazelnut"=>"Buy hazelnuts",
"have_hazelnut"=>"You currently have <span class='nombre-hazelnut'> %s </span> hazelnuts.",
 
"account_newemail"=>"New E-mail",
"account_code_verifed"=>"Successful validation. You can now edit account settings.",
"namechange_fraises"=>"Changing your name requires %s fraises.",
"namechange_newname"=>"New Name",
"account_shortlongname"=>"The name must be at least 3 characters and at most 15 characters.",
"account_fraisesnotenough"=>"Fraises is insufficient.",
"account_nameinusage"=>"This username is being used.",
"account_nameinusagebyyou"=>"You already use this username.",
"account_shortlongpw"=>"Password must be at least 8 characters and at most 16 characters.",
"account_pwsnotmatch"=>"Both your passwords must be identical.",
"account_pwchanged"=>"The password was changed !",
"account_blankemail"=>"E-mail field should not be left blank.",
"account_fakeemail"=>"Invalid email.",
"account_emailchanged"=>"E-mail has been changed!",
"verification_newpassword"=>"New password",
"verification_passwordvf"=>"Password verification",
"verification_exitall"=>"Sign out from all devices",
"move"=>"Move"

);

?>
