<?php
$plang = array(
"alt_bolumler" => "Подразделы",

"my_account"=>"Мой аккаунт",
"atelier801_account"=>"Аккаунт ".$ayarlar['title'],
"email_change"=>"Изменить почту",
"pw_change"=>"Изменить пароль",
"nick_change"=>"Сменить имя",
"buy_fraises"=>"Купить клубнику",
"verification_code"=>"Код",
"have_fraises"=>"На данный момент у вас <span class='nombre-fraises'>%s</span> клубники.",
"fraises_offer"=>"(%s бесплатно)",
"loading"=>"Загрузка...",
"verification_required"=>"Вы должны подтвердить аккаунт, чтобы получить доступ к редактированию его настроек.",
"verification_request"=>"Запросить подтверждение",
"verification_entercode"=>"Пожалуйста, введите код подтверждения, который пришёл вам на почту.",
"verification_unsuccessful"=>"Введённый код подтверждения недействителен.",
 
"language"=>"Язык",
"forums"=>"Форумы",
"dev_tracker"=>"Dev Tracker",
"arama"=>"Поиск",
"Inbox"=>"Входящие",
"last_posts"=>"Последние сообщения",
"favorite_topics"=>"Избранные темы",
"favorite_tribes"=>"Избранные племена",
"my_profile"=>"Мой профиль",
"my_friends"=>"Мои друзья",
"blacklist"=>"Чёрный список",
"my_tribe"=>"МОЁ ПЛЕМЯ",
"tribe_profile"=>"Профиль племени",
"tribe_forum"=>"Форум племени",
"see_members"=>"Посмотреть участников",
 
"required_nick"=>"Имя пользователя (обязательно)",
"contact"=>"Свяжитесь с нами",
"contact_text"=>"Есть что сказать? Пожелания, что бы вы хотели изменить или увидеть в ".$ayarlar['title']."? Напишите нам здесь!",
"required_email"=>"Адрес e-mail (обязательно)",
"category"=>"Категория",
"contact_1"=>"Проблема с оплатой",
"contact_2"=>"Смена e-mail",
"contact_4"=>"Потерян пароль",
"contact_6"=>"Обратная связь",
"contact_7"=>"Бизнес и деловые отношения ",
"contact_8"=>"Другое",
"subject"=>"Тема",
"topic_message"=>"Сообщение",
 
"chat"=>"Беседа",
"conversation_deleted"=>"You can no longer answer because the other person has deleted this conversation completely.",
 
"mark_not_seen"=>"Пометить, как непрочитанное",
"started_at_date1"=>"Создано ",
"started_at_date2"=>"",
"tumunu_sec"=>"Выбрать всё",
"tumunu_sec_kaldir"=>"Очистить всё",
"new_dialog"=>"Новое сообщение",
"new_discussion"=>"Новое обсуждение",
"new_private_poll"=>"Новый закрытый опрос",
"empty_trash"=>"Очистить корзину",
"delete_permanently"=>"Удалить навсегда",
"inbox"=>"Входящие",
"trash"=>"Корзина",
 
"topic"=>"Тема",
"topic_createdby1"=>" Создано ",
"topic_createdby2"=>" в ",
"topic_createdby3"=>"",
"delete_favoritetopic"=>"Удалить из избранного",
 
"favorite"=>"Favorite",
 
"team"=>"Команда",
"privacy"=>"Политика конфиденциальности",
"version"=>"Версия ".$ayarlar['version'],
"terms_cookie"=>"Этот сайт использует cookies для удобства работы. ",
"accept_text"=>"Понятно",
"terms_polit"=>"Политика конфиденциальности",
 
"reset_password"=>"Сбросить пароль",
"sifre"=>"Password",
"tekrar"=>"Again",
"mailtemp"=>'

<div>'.$ayarlar['title'].' %s<br>
<a href="'.$site.'" target="_blank">'.$site.'</a>
<hr>

<p>Someone, hopefully you, has requested to validate your  '.$ayarlar['title'].' account %1</p>

<p>For your select setting, please copy the following code into the appropriate input field in game : </p><h1>%2</h1><p></p>

<p>If you didn\'t request it, you can ignore this email.</p>
</div>

',
 

"login_keeplogged"=>"Запомнить меня",
"login_or"=>"ИЛИ",
 
"to_who"=>"Кому",
"message_subject"=>"Тема",
"dialog_yourself"=>"Имена игроков неверные, они игнорируют вас или находятся в вашем черном списке.",
 
"new_forum"=>"New Forum",
"edit_forum"=>"Edit Forum",
 
"new_section"=>"Новый раздел",
"edit_section"=>"Редактировать",
 
"topic_name"=>"Заголовок",
"bold"=>"Полужирный",
"italic"=>"Курсив",
"underlined"=>"Подчёркнутый",
"strikethrough"=>"Зачёркнутый",
"colorhex"=>"Цвет (hex-код)",
"size"=>"Размер",
"small"=>"Маленький",
"large"=>"Большой",
"huge"=>"Очень большой",
"font"=>"Шрифт",
"alignment"=>"Абзац",
"left"=>"Слева",
"right"=>"Справа",
"center"=>"По центру",
"justify"=>"По ширине",
"seperation"=>"Горизонтальная полоса",
"table"=>"Таблица",
"image"=>"Изображение: поместите URL между тегами",
"uitab"=>"Закладки: введите название после # между тегами",
"leftalign"=>"Выравнивание слева",
"rightalign"=>"Выравнивание справа",
"centeralign"=>"В центре",
"link"=>"Ссылка",
"list"=>"Список",
"quote"=>"Цитата",
"lock"=>"Спойлер",
"previsualisation"=>"Превью",
"previsualisation_hide"=>"Закрыть",
 
"messages"=>"Сообщений",
"prestige"=>"Престиж",
"profile_level"=>"Уровень престижа",
"profile_birth"=>"День рождения",
"profile_location"=>"Местонахождение",
"show_ifonline"=>"Показывать онлайн статус",
"online"=>"В сети",
"offline"=>"Не в сети",
"sanctions"=>"Санкции",
"ban_type"=>"Тип",
"ban_time"=>"Длительность",
"ban_created"=>"Создано",
"ban_start"=>"Начало",
"ban_end"=>"Окончание",
"ban_status"=>"Состояние",
"ban_active"=>"Активно",
"ban_ended"=>"Ended",
"ban_hour"=>"час(ов)",
"profile"=>"Профиль",
"send_message"=>"Отправить сообщение",
"change_avatar"=>"Изменить аватар",
"remove_avatar"=>"Удалить аватар",
"edit_profile"=>"Редактировать профиль",
"parameters"=>"Параметры",
"message_more"=>"Больше",
"message_less"=>"Меньше",
"started_topics"=>"Созданные темы",
"profiles"=>"Профили",
 
"new_topic"=>"Новая тема",
"new_forum_poll"=>"Новый опрос",
"pin"=>"Закрепить",
"unpin"=>"Unpin",
"lockf"=>"Закрыто",
"unlock"=>"Активно",
"filter_view"=>"Фильтр показа",
"deleted_topics"=>"удалённые темы",
 
"name"=>"Name",
"admins"=>"Admins",
"mods"=>"Moderators",
"sentinels"=>"Sentinels",
"mappers"=>"Map crews",
 
"add_favoritetopic"=>"Add from favorites",
"mudahale"=>"Moderated by %s, reason: %s",
"mudahale_text"=>"Moderate",
"last_edit"=>"Last edit:",
"topic_locked"=>"Topic locked",
 
"started_at_by"=>"by %s on %s",
 
"change_logo"=>"Change logo",
"remove_logo"=>"Remove logo",
"tribe_open"=>"Open",
"tribe_closed"=>"Closed",
"show_tribemessage"=>"Show tribal message",
"show_tribedescription"=>"Show description",
"tribe_message"=>"Tribal message",
"tribe_history"=>"История",
"tribes"=>"Tribes",
"page_next"=>"Next",
"page_last"=>"Last",
 
"email"=>"E-mail",
"isim"=>"Name",
"report_short"=>"Your report should consist of at least 3 words.",
 
"reconnection"=>"Connecting again...",
"autolang_error"=>"Automatic language opened because your language is not in the system.",
"not_found"=>"Not found",
"404_page"=>"Page not found.",
"reward"=>"Reward",
"yil"=>"Year(s)",
"ay"=>"Month(s)",
"gun"=>"Day(s)",
"saat"=>"Hour(s)",
"dakika"=>"Minute(s)",
"saniye"=>"Second(s)",
"reward_left"=>"Left",
"buy_hazelnut"=>"Buy hazelnuts",
"have_hazelnut"=>"You currently have <span class='nombre-hazelnut'> %s </span> hazelnuts.",
 
"account_newemail"=>"New E-mail",
"account_code_verifed"=>"Successful validation. You can now edit account settings.",
"namechange_fraises"=>"Changing your name requires %s fraises.",
"namechange_newname"=>"New Name",
"account_shortlongname"=>"The name must be at least 3 characters and at most 15 characters.",
"account_fraisesnotenough"=>"Fraises is insufficient.",
"account_nameinusage"=>"This username is being used.",
"account_nameinusagebyyou"=>"You already use this username.",
"account_shortlongpw"=>"Password must be at least 8 characters and at most 16 characters.",
"account_pwsnotmatch"=>"Both your passwords must be identical.",
"account_pwchanged"=>"The password was changed !",
"account_blankemail"=>"E-mail field should not be left blank.",
"account_fakeemail"=>"Invalid email.",
"account_emailchanged"=>"E-mail has been changed!",
"verification_newpassword"=>"New password",
"verification_passwordvf"=>"Password verification",
"verification_exitall"=>"Sign out from all devices",
"move"=>"Move"

);

?>
